In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4]

In [3]:
np.array(mylist)

array([1, 2, 3, 4])

In [4]:
type(mylist)

list

In [5]:
arr = np.array(mylist)

In [6]:
type(arr)

numpy.ndarray

In [8]:
a = np.arange(0,10)

In [9]:
arr = np.arange(0,10,2)

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
type(1.0)

float

In [14]:
type(1.)

float

In [15]:
np.random.rand(6)

array([0.23743659, 0.75870202, 0.72662017, 0.52501721, 0.31021157,
       0.76450403])

In [16]:
np.random.randn(1)

array([0.16888247])

In [17]:
np.random.randint(0,100,10)

array([ 6, 58, 63, 26, 19,  0, 79, 30, 53, 71])

In [18]:
np.random.randint(0,100)

96

In [19]:
np.random.randint(0,100,(5,5))

array([[97, 13, 34, 92, 83],
       [87, 19, 74, 99, 93],
       [82, 32, 42, 83, 67],
       [95, 59, 73, 66, 87],
       [50,  2, 84, 37, 66]])

In [21]:
np.linspace(1,20,50,retstep=True)

(array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
         2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
         4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
         6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
         8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
        10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
        12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
        14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
        16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
        18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ]),
 0.3877551020408163)

In [23]:
np.linspace(0,10,101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [24]:
np.random.seed(101)

In [25]:
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [26]:
arr = np.random.randint(0,100,10)

In [27]:
arr.max()

93

In [28]:
arr.min()

4

In [29]:
arr.argmax()

8

In [30]:
arr.argmin()

0

In [31]:
arr.dtype

dtype('int32')

In [32]:
arr.sort()

In [33]:
arr

array([ 4,  5, 12, 40, 40, 60, 63, 64, 92, 93])

In [34]:
arr.mean()

47.3

In [37]:
arr.size

10

In [38]:
arr.std()

31.28913549460899

In [39]:
arr.sum()

473

In [40]:
arr.ravel()

array([ 4,  5, 12, 40, 40, 60, 63, 64, 92, 93])

In [44]:
arr.reshape((5,2))

array([[ 4,  5],
       [12, 40],
       [40, 60],
       [63, 64],
       [92, 93]])

In [45]:
arr.shape

(10,)

In [46]:
mat = np.arange(0,100).reshape(10,10)

In [48]:
mat[5,2]

52

In [50]:
mat[:,-2]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [51]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])