In [1]:
# NumPy Indexing and Selection
#In this lecture we will discuss how to select elements or groups of elements from an array.

In [2]:
import numpy as np

In [3]:
#Creating sample array
arr = np.arange(0,11)

In [4]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
## Bracket Indexing and Selection
#The simplest way to pick one or some elements of an array looks very similar to python lists:

In [6]:
#Get a value at an index
arr[8]

8

In [7]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [8]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
## Broadcasting
#Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [10]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [15]:
#Now note the changes also occur in our original array!

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
#Data is not copied, it's a view of the original array! This avoids memory problems!

In [18]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
## Indexing a 2D array (matrices)

#The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [20]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [23]:
# Format is arr_2d[row][col] or arr_2d[row,col]
# Getting individual element value
arr_2d[1][0]

20

In [24]:
# Getting individual element value
arr_2d[1,0]

20

In [25]:
# 2D array slicing
#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [26]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [27]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [29]:
## More Indexing Help
#Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. 
#Try google image searching NumPy indexing to fins useful images, like this one:

In [30]:
## Conditional Selection
#This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part!
#Let's briefly go over how to use brackets for selection based off of comparison operators.

In [31]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [33]:
bool_arr = arr>4

In [34]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
x =arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
### Slicing:
#Similar to Python lists, numpy arrays can be sliced. 
#Since arrays may be multidimensional, you must specify a slice for each dimension of the array:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
#b = a[:3,1:3]
print (b)

[[2 3]
 [6 7]]


In [40]:
#You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original
#array. Note that this is quite different from the way that MATLAB handles array slicing:

In [41]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)

print()
print (col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [43]:
## Integer array indexing: 
#When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array.
#In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. 
#Here is an example:

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print (a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print (np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [ ]:
# Great Job

#ML forum VIIT