In [1]:
# NumPy Operations

In [2]:
## Arithmetic

#You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [3]:
import numpy as np
arr = np.arange(0,10)

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

D:\ANACONDA\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
# Also warning, but not an error instead infinity
1/arr

D:\ANACONDA\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [10]:
## Universal Array Functions
#Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are 
#essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [11]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [12]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [13]:
np.max(arr) #same as arr.max()

9

In [14]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [15]:
np.log(arr)

D:\ANACONDA\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [16]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print('x= ',x)
print()
print('y= ',y)
print()
# Elementwise sum; both produce the array
print( x + y)
print (np.add(x, y))

x=  [[1. 2.]
 [3. 4.]]

y=  [[5. 6.]
 [7. 8.]]

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [17]:
# Elementwise difference; both produce the array
print (x - y)
print (np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [18]:
# Elementwise product; both produce the array
print (x * y)
print (np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [19]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print (x / y)
print (np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [20]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print (np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [21]:
#Note that `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner 
#products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the 
#numpy module and as an instance method of array objects:

In [2]:
import numpy as np
x = np.array([[1,2],[3,4]])
x
print (np.sum(x) ) # Compute sum of all elements; prints "10"
print (np.sum(x, axis=0) ) # Compute sum of each column; prints "[4 6]"
print (np.sum(x, axis=1) ) # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [23]:
#Broadcasting

#Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic 
#operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times
#to perform some operation on the larger array.

#For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x (what if we use y=x ?)
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print( y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [24]:
#This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow.
#Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies
#of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [25]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print (vv)                 # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [26]:
y = x + vv  # Add x and vv elementwise
print (y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [28]:
#Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v.
#Consider this version, using broadcasting:

In [ ]:
'''
The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works
as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the 
   same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the
   arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves
   as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation]
(http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all
universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:
'''


In [ ]:
#This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. 
#Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
print(v*w)
#print (np.reshape(v, (3, 1)) * w)

In [ ]:
# Add a vector to each row of a matrix
x =( np.array([[1,2,3], [4,5,6]]))
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print (x + v) 

In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print( (x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print (x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print (x * 2)

In [1]:
#This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete.
#Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

In [ ]:
# Great Job

#ML forum VIIT